---

- name: apt install certbot
  apt:
    name: "letsencrypt"
    state: present
    update_cache: yes
  become: yes

- name: check certificate file existence
  stat:
    path: /etc/letsencrypt/live/gobel.tk/cert.pem
  register: cert_file

// TODO: webrootに変更
- name: create a certificate file for the first time to create
  command: certbot certonly --standalone -d gobel.tk --agree-tos --renew-by-default -m "bmf.infomation@gmail.com"
  when: not cert_file.stat.exists
  become: yes

// TODO: 
- name: Set up cron for certificate renewal
  cron:
    name="renew-cert"
　  month="1,3,5,7,9,11"
    minute="0"
    hour="4"
    day="1"
    // TODO: webrootに変更する。証明書を自動更新するにはwebrootじゃないとだめ。なので先にgobel-exampleのデプロイをすすめる
    ex.  certbot certonly -n --keep-until-expiring --agree-tos --webroot --webroot-path /var/lib/letsencrypt -m ${LETSENCRYPT_MAIL} -d ${HOST}
    job='/usr/bin/systemctl stop httpd24-httpd.service && /usr/bin/certbot renew --force-renew --quiet --post-hook "/usr/bin/systemctl start httpd24-httpd.service"'
    user=root
    cron_file=renew_cert