---

- name: configure rsyslog
  become: true
  lineinfile:
    dest: "/etc/rsyslog.d/50-default.conf"
    line: "cron.*                           /var/log/cron.log"
    regexp: "^#cron"
    create: yes

- name: restart rsyslog
  become: true
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: configure cron logging
  become: true
  lineinfile:
    dest: "/etc/default/cron"
    line: "EXTRA_OPTS='-L 15'"

- name: restart crontab
  become: true
  systemd:
    name: cron
    state: restarted
    enabled: yes

- name: input a database name
  pause: prompt="Input a database name"
  register: database_name

- name: input a database password
  pause: prompt="Input a database password"
  register: database_password

- name: set cron for backup database
  become: true
  ansible.builtin.cron:
    name: certbot renew
    user: "{{ ssh_user_name }}"
    minute: '0'
    hour: '3'
    job: docker exec gobel-mysql mysqldump {{database_name.user_input}} -uroot -p{{database_password.user_input}} > backup.sql
    state: present
    cron_file: bmf-tech_database

- name: set cron for renewing certificates
  become: true
  ansible.builtin.cron:
    name: certbot renew
    user: "{{ ssh_user_name }}"
    minute: '0'
    hour: '0'
    day: '*'
    month: '*'
    weekday: '0' # Sunday
    job: docker run --rm -e CONOHA_POLLING_INTERVAL=30 -e CONOHA_PROPAGATION_TIMEOUT=3600 -e CONOHA_TTL=3600 -e CONOHA_REGION={{ conoha_region }} -e CONOHA_TENANT_ID={{ conoha_tenant_id }} -e CONOHA_API_USERNAME={{ conoha_username }} -e CONOHA_API_PASSWORD={{ conoha_password }} -v {{ path_to_certificates_directory }}:/certificates goacme/lego --path /certificates --email {{ email }} --dns conoha --domains *.{{ domain }} --domains {{ domain }} --accept-tos renew
    state: present
    cron_file: bmf-tech_certificates