---

- name: change iptables for accepting new ssh connections
  iptables:
    chain: "INPUT"
    protocol: "tcp"
    destination_port: "{{ ssh_port | int }}"
    ctstate: "NEW"
    syn: "match"
    jump: "ACCEPT"
    comment: "Accept new SSH connections."

- name : add a ssh user
  user: 
    name: "{{ ssh_user_name }}"
    password: "{{ ssh_user_password | password_hash('sha512') }}"
    shell: "/bin/bash"
    state: "present"
    groups: "sudo"

- name: make a .ssh directory
  file: 
    path: "~{{ ssh_user_name }}/.ssh"
    state: "directory"
    owner: "{{ ssh_user_name }}"
    group: "{{ ssh_user_name }}"
    mode: 0700

- name: copy a public key to an authorized_keys
  copy: 
    dest: "~{{ ssh_user_name }}/.ssh/authorized_keys"
    content: "{{ public_key }}"
    mode: 0600
    owner: "{{ ssh_user_name }}"
    group: "{{ ssh_user_name }}"

- name: change sshd_config for changing a port number for ssh
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    insertafter: "^#Port"
    line: "Port {{ ssh_port }}"

- name: change sshd_config for disabling password authentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    insertafter: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify:
    - restart sshd

- name: change sshd_config for disabling permit root login
  lineinfile:
    dest: "/etc/ssh/sshd_config" 
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: "present"
  notify:
    - restart sshd