---

- name: apt install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add GPG key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Add apt repository for docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: yes

- name: apt install docker packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce=5:19.03.9~3-0~ubuntu-focal
  become: yes

- name:  Add user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes

- name: Verify that the docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
