---

- name: apt update
  apt:
    update_cache: yes
  become: yes

- name: install the list of packages by apt
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - make