---

- name: apt update
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: install the list of packages by apt
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - make
      - jq
      - certbot
