---

- name: Init kubernetes cluster
  become: yes
  shell: |
    kubeadm init --node-name master --pod-network-cidr=10.244.0.0/16

- name: Create kubernetes config directory
  file:
    path: "~{{ new_user_name }}/.kube/"
    state: directory

- name: Copy admin.conf to home directory
  become: yes
  copy:
    src: "/etc/kubernetes/admin.conf" 
    dest: "~{{ new_user_name }}/.kube/config"
    owner: "{{ new_user_name }}"
    group: "{{ new_user_name }}"
    mode: 0755
    remote_src: true

- name: Update kernel settings for installing flannel
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Install flannel
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    
# TODO: worker用意するのでmasterにデプロイできるにしなくてもいいや
# - name: Remove the taint to be able to deploy to master
#   become: yes
#   shell: |
#     kubectl taint nodes --all node-role.kubernetes.io/master-

- name: Generate a token
  shell: |
    kubeadm token generate
  register: kubeadm_token
  run_once: true
